% fill color 0
color clrsCfA;
clrsCfA := (1.0,0.9,0.67);
% fill color 1
color clrsCfB;
clrsCfB := (0.7,0.9,1.0);
% fill color 2
color clrsCfC;
clrsCfC := (0.95,0.95,0.9);
color clrsCfD;
clrsCfD := (0.95,0.95,0.6);
color clrsCfE;
clrsCfE := (0.0,0.52,0.71);

% line color 0
color clrsClA;
clrsClA := (1.0,0.5,0);
% line color 1
color clrsClB;
clrsClB := (0.3,0.6,0.9);
color clrsClC;
clrsClC := (0.71,0.57,0.44);
